<template>
  <div class="page" v-loading="loading">
    <section class="metrics"><div><span>正式项目</span><strong>{{ data.total||0 }}</strong></div><div><span>计划中</span><strong>{{ data.planning||0 }}</strong></div><div><span>执行中</span><strong>{{ data.active||0 }}</strong></div><div><span>结项中</span><strong>{{ data.closing||0 }}</strong></div><div><span>已结项</span><strong>{{ data.closed||0 }}</strong></div></section>
    <section class="grid">
      <div class="panel"><div class="head"><strong>项目组合</strong><span>按正式项目当前状态</span></div><div class="bars"><div v-for="s in distribution" :key="s.label"><div><span>{{ s.label }}</span><b>{{ s.value }}</b></div><el-progress :percentage="data.total?Math.round(s.value*100/data.total):0" :show-text="false" :stroke-width="7"/></div></div></div>
      <div class="panel"><div class="head"><strong>治理健康度</strong><span>开放风险与问题</span></div><div class="health"><div><span>开放风险</span><strong>{{ openRisks }}</strong></div><div><span>高/重大风险</span><strong class="danger">{{ highRisks }}</strong></div><div><span>开放问题</span><strong>{{ openIssues }}</strong></div><div><span>高严重度问题</span><strong class="danger">{{ highIssues }}</strong></div></div></div>
    </section>
    <section class="panel table"><div class="head"><strong>项目预算与进度</strong><span>用于组合视角，不替代财务系统</span></div><el-table :data="data.projects||[]"><el-table-column prop="projectNo" label="编号" width="130"/><el-table-column prop="projectName" label="项目" min-width="230"/><el-table-column prop="status" label="状态" width="90"/><el-table-column label="进度" width="110"><template #default="{row}">{{ row.progress||0 }}%</template></el-table-column><el-table-column label="当前预算" width="130" align="right"><template #default="{row}">¥{{ money(row.currentBudget) }}</template></el-table-column><el-table-column label="已支出" width="130" align="right"><template #default="{row}">¥{{ money(row.usedBudget) }}</template></el-table-column><el-table-column label="风险" width="70" align="center"><template #default="{row}">{{ row.openRiskCount||0 }}</template></el-table-column><el-table-column label="问题" width="70" align="center"><template #default="{row}">{{ row.openIssueCount||0 }}</template></el-table-column></el-table></section>
  </div>
</template>
<script setup>
import { getResearchAnalytics } from '@/api/research'
const loading=ref(false),data=reactive({projects:[],risks:[],issues:[]})
async function load(){loading.value=true;try{const r=await getResearchAnalytics();Object.assign(data,r.data||{})}finally{loading.value=false}}
const distribution=computed(()=>[{label:'计划中',value:data.planning||0},{label:'执行中',value:data.active||0},{label:'结项中',value:data.closing||0},{label:'已结项',value:data.closed||0}])
const openRisks=computed(()=>data.risks?.filter(x=>x.status!=='CLOSED').length||0),highRisks=computed(()=>data.risks?.filter(x=>['HIGH','CRITICAL'].includes(x.riskLevel)&&x.status!=='CLOSED').length||0),openIssues=computed(()=>data.issues?.filter(x=>!['RESOLVED','CLOSED'].includes(x.status)).length||0),highIssues=computed(()=>data.issues?.filter(x=>['HIGH','CRITICAL'].includes(x.severity)&&!['RESOLVED','CLOSED'].includes(x.status)).length||0)
function money(v){return Number(v||0).toLocaleString()}
onMounted(load)
</script>
<style scoped lang="scss">
.page{display:flex;flex-direction:column;gap:10px}.metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.metrics>div{padding:9px 11px;border:1px solid var(--rf-border);border-radius:9px;background:var(--rf-surface);display:flex;justify-content:space-between;align-items:center}.metrics span{font-size:10px;color:var(--rf-text-muted)}.metrics strong{font-size:19px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.panel{border:1px solid var(--rf-border);border-radius:10px;background:var(--rf-surface);overflow:hidden}.head{padding:9px 11px;border-bottom:1px solid var(--rf-border);display:flex;justify-content:space-between}.head strong{font-size:12px}.head span{font-size:10px;color:var(--rf-text-muted)}.bars{padding:12px;display:grid;gap:12px}.bars>div>div{margin-bottom:5px;display:flex;justify-content:space-between;font-size:10px}.health{padding:12px;display:grid;grid-template-columns:1fr 1fr;gap:8px}.health>div{padding:10px;border:1px solid var(--rf-border);border-radius:8px;display:flex;justify-content:space-between}.health span{font-size:10px;color:var(--rf-text-muted)}.health strong{font-size:18px}.danger{color:var(--rf-danger)}.table .head{border-bottom:0}@media(max-width:800px){.metrics{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:1fr}}
</style>
