import request from '@/utils/request'

export const getResearchDashboard = () => request({ url: '/research/dashboard', method: 'get' })
export const getResearchAnalytics = () => request({ url: '/research/analytics', method: 'get' })

export const listResearchProposals = params => request({ url: '/research/proposals', method: 'get', params })
export const getResearchProposal = id => request({ url: \`/research/proposals/\${id}\`, method: 'get' })
export const createResearchProposal = data => request({ url: '/research/proposals', method: 'post', data })
export const updateResearchProposal = (id, data) => request({ url: \`/research/proposals/\${id}\`, method: 'put', data })
export const validateResearchProposal = id => request({ url: \`/research/proposals/\${id}/validation\`, method: 'get' })
export const submitResearchProposal = id => request({ url: \`/research/proposals/\${id}/submit\`, method: 'post' })
export const approveResearchProposal = (id, comment='') => request({ url: \`/research/proposals/\${id}/approve\`, method: 'post', data: { comment } })
export const rejectResearchProposal = (id, comment='') => request({ url: \`/research/proposals/\${id}/reject\`, method: 'post', data: { comment } })
export const issueResearchAward = (id, data={}) => request({ url: \`/research/proposals/\${id}/award\`, method: 'post', data })

export const listResearchProjects = params => request({ url: '/research/projects', method: 'get', params })
export const getResearchProject = id => request({ url: \`/research/projects/\${id}\`, method: 'get' })
export const activateResearchProject = id => request({ url: \`/research/projects/\${id}/activate\`, method: 'post' })
export const addResearchWorkItem = (id, data) => request({ url: \`/research/projects/\${id}/work-items\`, method: 'post', data })
export const researchWorkItemAction = (id, workItemId, action) => request({ url: \`/research/projects/\${id}/work-items/\${workItemId}/\${action}\`, method: 'post' })
export const addResearchProgressReport = (id, data) => request({ url: \`/research/projects/\${id}/progress-reports\`, method: 'post', data })
export const addResearchRisk = (id, data) => request({ url: \`/research/projects/\${id}/risks\`, method: 'post', data })
export const occurResearchRisk = (id, riskId, data={}) => request({ url: \`/research/projects/\${id}/risks/\${riskId}/occur\`, method: 'post', data })
export const addResearchIssue = (id, data) => request({ url: \`/research/projects/\${id}/issues\`, method: 'post', data })
export const resolveResearchIssue = (id, issueId, resolution) => request({ url: \`/research/projects/\${id}/issues/\${issueId}/resolve\`, method: 'post', data: { resolution } })
export const createResearchChange = (id, data) => request({ url: \`/research/projects/\${id}/changes\`, method: 'post', data })
export const submitResearchChange = (id, changeId) => request({ url: \`/research/projects/\${id}/changes/\${changeId}/submit\`, method: 'post' })
export const approveResearchChange = (id, changeId, comment='') => request({ url: \`/research/projects/\${id}/changes/\${changeId}/approve\`, method: 'post', data: { comment } })
export const rejectResearchChange = (id, changeId, comment='') => request({ url: \`/research/projects/\${id}/changes/\${changeId}/reject\`, method: 'post', data: { comment } })
export const applyResearchChange = (id, changeId) => request({ url: \`/research/projects/\${id}/changes/\${changeId}/apply\`, method: 'post' })
export const addResearchExpense = (id, data) => request({ url: \`/research/projects/\${id}/expenses\`, method: 'post', data })
export const addResearchOutcome = (id, data) => request({ url: \`/research/projects/\${id}/outcomes\`, method: 'post', data })
export const submitResearchAcceptance = (id, data) => request({ url: \`/research/projects/\${id}/acceptance\`, method: 'post', data })
export const approveResearchAcceptance = (id, comment='') => request({ url: \`/research/projects/\${id}/acceptance/approve\`, method: 'post', data: { comment } })
export const rejectResearchAcceptance = (id, comment='') => request({ url: \`/research/projects/\${id}/acceptance/reject\`, method: 'post', data: { comment } })
export const completeResearchCloseout = (id, data) => request({ url: \`/research/projects/\${id}/closeout\`, method: 'post', data })

export const listResearchApprovals = () => request({ url: '/research/approvals', method: 'get' })
export const listResearchRisks = () => request({ url: '/research/risks', method: 'get' })
export const generateResearchProposal = description => request({ url: '/research/ai/proposal', method: 'post', data: { description } })
